### ISSUE TITLE
Полнотекстовый поиск с учётом русского

### ISSUE THREAD

**Issue by Oreolek** [Oreolek/ifhub-skin#7]
Идеальный вариант - Sphinx, но он требует ресурсов VPS и плагина для LiveStreet 2 ещё нет, так что писать самому.

**Comment by epoxa** [comment]
А сейчас на каком сервере оно крутится?

**Comment by Oreolek** [comment]
На моём основном, вместе с oreolek.ru.

Сфинкс по природе должен держать в памяти полнотекстовый индекс по всем статьям, то есть, на него нужно выделить память. Для этого нужно хорошо просчитать, сколько не страшно занять памяти так, чтобы сайт не начал валиться с наплывом посетителей. А для этого нужна точная статистика по посетителям.

Выходит, что есть два варианта: срочно собирать донат и апгрейдить сервер или ждать, когда соберётся статистика и садиться за скрупулёзные вычисления. Пока что жду.

**Comment by Oreolek** [comment]
LS 2 официально не поддерживает Sphinx, так что задача пока в очень долгом ящике.
